### ISSUE TITLE
[Refactoring] CSS 개선

### ISSUE THREAD

**Issue by 0xTeoo** [codestates/MDNplus-client-#156]
# Task Card

## 개선할 기능
프로젝트 전반적으로 무의미한 css 스타일링을 위한 컴포넌트가 작성되어있다. styled-component에 내장된 scss 기능을 사용하여 전반적으로 리팩토링 할 예정

## 해야 할 일
- [x] 무의미한 스타일 컴포넌트 제거 후, class 설정
   - [x] 랜딩페이지 css 수정
   - [x] 헬프데스크 css 수정
   - [x] 위키 css 수정
   - [x] #161
- [x] 재사용 가능한 버튼 컴포넌트 구현
- [x] 재사용 가능한 모달 컴포넌트 구현
- [x] 재사용 가능한 작성 페이지 레이아웃 컴포넌트 구현
